name: PublishDemo

on:
  pull_request:
    types:
      - closed

jobs:
  publish-demo:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'ready')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config --global github.user akshay5995
      - run: git config --global github.email akshay5995@gmail.com
      - run: git config --global github.token ${{secrets.GITHUB_TOKEN}} 
      - run: npm install
      - run: npm run publish:demo
